/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static float *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->a, argp->b, rqstp));
}

static float *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->a, argp->b, rqstp));
}

static float *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->a, argp->b, rqstp));
}

static float *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->a, argp->b, rqstp));
}

static float *
_seno_1 (float  *argp, struct svc_req *rqstp)
{
	return (seno_1_svc(*argp, rqstp));
}

static float *
_coseno_1 (float  *argp, struct svc_req *rqstp)
{
	return (coseno_1_svc(*argp, rqstp));
}

static float *
_tangente_1 (float  *argp, struct svc_req *rqstp)
{
	return (tangente_1_svc(*argp, rqstp));
}

static float *
_arcoseno_1 (float  *argp, struct svc_req *rqstp)
{
	return (arcoseno_1_svc(*argp, rqstp));
}

static float *
_arcocoseno_1 (float  *argp, struct svc_req *rqstp)
{
	return (arcocoseno_1_svc(*argp, rqstp));
}

static float *
_arcotangente_1 (float  *argp, struct svc_req *rqstp)
{
	return (arcotangente_1_svc(*argp, rqstp));
}

static float *
_raiz_cuadrada_1 (float  *argp, struct svc_req *rqstp)
{
	return (raiz_cuadrada_1_svc(*argp, rqstp));
}

static float *
_potencia_1 (potencia_1_argument *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(argp->a, argp->b, rqstp));
}

static float_array *
_suma_vectores_1 (suma_vectores_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_vectores_1_svc(argp->a, argp->b, rqstp));
}

static float_array *
_resta_vectores_1 (resta_vectores_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_vectores_1_svc(argp->a, argp->b, rqstp));
}

static float *
_producto_escalar_1 (producto_escalar_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_escalar_1_svc(argp->a, argp->b, rqstp));
}

static float_array *
_producto_vectorial_1 (producto_vectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_vectorial_1_svc(argp->a, argp->b, rqstp));
}

static float_matrix *
_suma_matrices_1 (suma_matrices_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_matrices_1_svc(argp->a, argp->b, rqstp));
}

static float_matrix *
_resta_matrices_1 (resta_matrices_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_matrices_1_svc(argp->a, argp->b, rqstp));
}

static float_matrix *
_multiplicacion_matrices_1 (multiplicacion_matrices_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_matrices_1_svc(argp->a, argp->b, rqstp));
}

static float_matrix *
_division_matriz_real_1 (division_matriz_real_1_argument *argp, struct svc_req *rqstp)
{
	return (division_matriz_real_1_svc(argp->a, argp->b, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		resta_1_argument resta_1_arg;
		division_1_argument division_1_arg;
		float seno_1_arg;
		float coseno_1_arg;
		float tangente_1_arg;
		float arcoseno_1_arg;
		float arcocoseno_1_arg;
		float arcotangente_1_arg;
		float raiz_cuadrada_1_arg;
		potencia_1_argument potencia_1_arg;
		suma_vectores_1_argument suma_vectores_1_arg;
		resta_vectores_1_argument resta_vectores_1_arg;
		producto_escalar_1_argument producto_escalar_1_arg;
		producto_vectorial_1_argument producto_vectorial_1_arg;
		suma_matrices_1_argument suma_matrices_1_arg;
		resta_matrices_1_argument resta_matrices_1_arg;
		multiplicacion_matrices_1_argument multiplicacion_matrices_1_arg;
		division_matriz_real_1_argument division_matriz_real_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case SENO:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _seno_1;
		break;

	case COSENO:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _coseno_1;
		break;

	case TANGENTE:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _tangente_1;
		break;

	case ARCOSENO:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _arcoseno_1;
		break;

	case ARCOCOSENO:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _arcocoseno_1;
		break;

	case ARCOTANGENTE:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _arcotangente_1;
		break;

	case RAIZ_CUADRADA:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _raiz_cuadrada_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_potencia_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case SUMA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_suma_vectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_array;
		local = (char *(*)(char *, struct svc_req *)) _suma_vectores_1;
		break;

	case RESTA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_resta_vectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_array;
		local = (char *(*)(char *, struct svc_req *)) _resta_vectores_1;
		break;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_producto_escalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_1;
		break;

	case PRODUCTO_VECTORIAL:
		_xdr_argument = (xdrproc_t) xdr_producto_vectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_array;
		local = (char *(*)(char *, struct svc_req *)) _producto_vectorial_1;
		break;

	case SUMA_MATRICES:
		_xdr_argument = (xdrproc_t) xdr_suma_matrices_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_matrix;
		local = (char *(*)(char *, struct svc_req *)) _suma_matrices_1;
		break;

	case RESTA_MATRICES:
		_xdr_argument = (xdrproc_t) xdr_resta_matrices_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_matrix;
		local = (char *(*)(char *, struct svc_req *)) _resta_matrices_1;
		break;

	case MULTIPLICACION_MATRICES:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_matrices_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_matrix;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_matrices_1;
		break;

	case DIVISION_MATRIZ_REAL:
		_xdr_argument = (xdrproc_t) xdr_division_matriz_real_1_argument;
		_xdr_result = (xdrproc_t) xdr_float_matrix;
		local = (char *(*)(char *, struct svc_req *)) _division_matriz_real_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALC);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALC, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALC, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALC, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALC, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
