/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_float_array (XDR *xdrs, float_array *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vector, 1000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tam))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_float_matrix (XDR *xdrs, float_matrix *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->m, 1000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tam1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tam2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_1_argument (XDR *xdrs, suma_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacion_1_argument (XDR *xdrs, multiplicacion_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_1_argument (XDR *xdrs, resta_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_division_1_argument (XDR *xdrs, division_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_potencia_1_argument (XDR *xdrs, potencia_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_vectores_1_argument (XDR *xdrs, suma_vectores_1_argument *objp)
{
	 if (!xdr_float_array (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_array (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_vectores_1_argument (XDR *xdrs, resta_vectores_1_argument *objp)
{
	 if (!xdr_float_array (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_array (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_escalar_1_argument (XDR *xdrs, producto_escalar_1_argument *objp)
{
	 if (!xdr_float_array (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_array (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_vectorial_1_argument (XDR *xdrs, producto_vectorial_1_argument *objp)
{
	 if (!xdr_float_array (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_array (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_matrices_1_argument (XDR *xdrs, suma_matrices_1_argument *objp)
{
	 if (!xdr_float_matrix (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_matrix (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_matrices_1_argument (XDR *xdrs, resta_matrices_1_argument *objp)
{
	 if (!xdr_float_matrix (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_matrix (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacion_matrices_1_argument (XDR *xdrs, multiplicacion_matrices_1_argument *objp)
{
	 if (!xdr_float_matrix (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float_matrix (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_division_matriz_real_1_argument (XDR *xdrs, division_matriz_real_1_argument *objp)
{
	 if (!xdr_float_matrix (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
